Improvement of the zenith interpolation with more control for the user
mdebony/acceptance_modelisation pull request #29
Opened 2024-07-22 15:05 UTC by mdebony

I've added an option to switch between a linear and logarithmic interpolation for the background model.
I've also added an experimental cleaning procedure to remove bad pixels from the interpolated background model that where the cause of issue when fitting the normalization of the background.
The overall code for interpolation was also a bit reorganized.

2024-07-23 14:26 UTC, gabemery requested changes
Quick review assuming all functionalities are working.

2024-07-24 08:00 UTC, mdebony commented on acceptance_modelisation/base_acceptance_map_creator.py
> +        if len(dict_binned_model) <= 1:
True, this is not needed anymore with the refactoring.

2024-07-24 09:21 UTC, mdebony commented on acceptance_modelisation/base_acceptance_map_creator.py
> +from .toolbox import compute_rotation_speed_fov, get_unique_wobble_pointings, get_time_mini_irf, \
Done

2024-07-24 09:55 UTC, gabemery approved these changes
Approved

2024-07-24 11:53 UTC, merged